name: Create issue to update resume

on:
  schedule:
    - cron: "0 0 1 */3 *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create issue by template
        id: create-issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          assignees: ${{ github.repository_owner }}
          filename: .github/update-resume.md

      - name: Check result
        run: |
          'echo Created issue number ${{ steps.create-issue.outputs.number }}'
          'echo Created ${{ steps.create-issue.outputs.url }}'
